#h2

#spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2
#  datasource:
#    url: jdbc:h2:mem:test
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true

#mysql

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/project?serverTimezone=Asia/Seoul
    username: root
    password: 1

#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://pre-1.cmybsu4mit3w.us-east-1.rds.amazonaws.com:3306/predatabase?serverTimezone=Asia/Seoul
#    username: admin
#    password: 12345678




